### ISSUE TITLE
Webhook config for Falco

### ISSUE THREAD

**Issue by bygui86** [opsgenie/kubernetes-event-exporter#108]
Hi guys,

I'm trying to integrate kubernetes-event-exporter with Sysdig Falco.
For now I was not lucky.

Does someone know if this integration is possible? If yes, how to configure it?

Thanks in advance for any help!

**Comment by mustafaakin-atl** [comment]
Not used Falco, but if it has a webhook, then you can integrate it. Layout allows full body customization.
