### ISSUE TITLE
Project maintanence 

### ISSUE THREAD

**Issue by oded-dd** [opsgenie/kubernetes-event-exporter#118]
I really like the work that was done here, but the project seems not to going forward, 
Are you continuing maintaining it? can I join and help?

**Comment by mrsiejas** [comment]
Would be great if the ownership will be sorted out sooner than later. It is an interesting project, with lot of community interest and potential but lack of updates makes it a show stopper for many of us. My PR has been dangling for a few months now.

**Comment by oded-dd** [comment]
@mustafaakin we would like to know if there is a plan to continue the work on the project, if not please let us know as we need to look for an alternatives

**Comment by mustafaakin** [comment]
Hello there, sorry for the delays. We will merge all the PRs (if ok) and most of the outstanding issues, and release the Docker image to ECR (because of Docker Hub public image limits) by 13 Jun.

**Comment by oded-dd** [comment]
Any update?

**Comment by michaelgeorgeattard** [comment]
Hello, first of all thank you for the awesome work put into this project.

We are anxiously waiting for a fix to the `/dev/stdout` file rotation issue causing `kubernetes-event-exporter` to stop emitting logs after a while.

**Comment by hevans-dglcom** [comment]
@michaelgeorgeattard we at Douglas have forked the project and fixed this issue ourselves. (version 1.0.2 in our dockerhub repo) if you are desperate to use it asap.

https://github.com/Parfuemerie-Douglas/kubernetes-event-exporter#stdout

https://hub.docker.com/r/parfuemeriedouglas/kubernetes-event-exporter

**Comment by mustafaakin-atl** [comment]
Hello, I merged the changes and will be publishing a new image soon.

**Comment by mustafaakin-atl** [comment]
See https://github.com/opsgenie/kubernetes-event-exporter/releases/tag/v0.10

**Comment by oded-dd** [comment]
Thank you so much!

**Comment by michaelgeorgeattard** [comment]
Thank you!
