### ISSUE TITLE
Unable to push Kubernetes events to a Kinesis stream.

### ISSUE THREAD

**Issue by ahmedmfadel** [opsgenie/kubernetes-event-exporter#119]
I tested Kubernetes event exporter's chart maintained by Bitnami and It works fine in collecting Kubernetes events from all namespaces. 

My issue is that I need to push these events to a Kinesis stream, I created a role that contains action PutObject on the desired Kinesis stream and attached it to the Pod using Kube2IAM, but when I check the logs I see the following event "No valid credentials provided" 

So my questions is Do I need to share an access key and secret key as environment variables inside the Pod in order to connect to Kinesis and push the events to it?

**Comment by mustafaakin-atl** [comment]
It uses the default credential chain, with no modifications. Therefore, it's a configuration issue with your identity provider.
