### ISSUE TITLE
Quickstart yaml uses incorrect key

### ISSUE THREAD

**Issue by alexanderwise** [opsgenie/kubernetes-event-exporter#12]
It looks like the yaml to create the default configmap for elasticsearch uses "receivers.elasticsearch.addresses" as the key here,

https://github.com/opsgenie/kubernetes-event-exporter/blob/master/deploy/01-config.yaml#L14

but, per the README it should be "receivers.elasticsearch.hosts"

Using "hosts" configures it to point to the the right target, whereas "addresses" seems to default to http://localhost:9200/

If it is supposed to be hosts instead of addresses, I'm happy to open the MR to correct it.

**Comment by mustafaakin** [comment]
Thanks, I have fixed the config file.
