### ISSUE TITLE
Move Elasticsearch username and password from configmap to Kubernetes secret

### ISSUE THREAD

**Issue by soleimaniamir** [opsgenie/kubernetes-event-exporter#140]
Hello,
I think this is not appropriate to store Elasticsearch username and password in form of the cleartext in Kubernetes configmap and it should move to a secret.

**Comment by mustafaakin-atl** [comment]
Kubernetes secrets are also plaintext if you have read access. Base64 is not encryption. People generally restrict access to Secret objects to ensure it's not readable by anyone.

**Comment by soleimaniamir** [comment]
yes of course, but it is possible to restrict user access to secrets but there is no way to do that for configmap, so I think it is better to move Elasticsearch username and password to secret.

**Comment by mustafaakin-atl** [comment]
Most of the RBAC can be achieved with Roles/ClusterRoles for any object (incuding configmaps) and API verb (get, put, delete)

See: https://kubernetes.io/blog/2017/10/using-rbac-generally-available-18/
