### ISSUE TITLE
Elasticsearch Index Append Date to Name

### ISSUE THREAD

**Issue by toddexp** [opsgenie/kubernetes-event-exporter#15]
The default value for indices sent to Elasticsearch is to append the date [(doc)](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-index). It would be nice to have the option to add the date to the end of the index that the kubernetes-event-exporter makes.

I tried to add the date to the end of an index in the configmap with the format found in that doc and the messages never made it to Elastic.

**Comment by toddexp** [comment]
Looks like this [PR](https://github.com/opsgenie/kubernetes-event-exporter/pull/18) should resolve the issue.

**Comment by mustafaakin** [comment]
#18 solves this.
