### ISSUE TITLE
Update version of aws-sdk-go in go.mod to latest

### ISSUE THREAD

**Issue by bitzhjr** [opsgenie/kubernetes-event-exporter#156]
### What would you like to be added:
Hello, I found that the version of aws-sdk-go used in kubernetes-event-exporter is too old(v1.30.10, the latest version is v1.41.12), Which may exist some cve vulnerabilities. Do we have the plan to upgrade?
### Why is this needed:
![image](https://user-images.githubusercontent.com/28079744/139211782-f2a2870d-86c6-4831-8139-84b14ddde552.png)

**Comment by mustafaakin-atl** [comment]
Updated aws and k8s dependencies to latest.
