### ISSUE TITLE
Support basic metadata on custom resources

### ISSUE THREAD

**Issue by amarrella** [opsgenie/kubernetes-event-exporter#17]
Hi, thanks for this project! It makes exporting events out of kubernetes very simple!

I'd like to post this feature request. With some guidance I can try to open a PR myself to implement it if you think it's a valid case.

At the moment the event exporter is not able to read metadata for custom resources and logs the error, for example:
```
2020-01-21T18:25:47Z ERR app/pkg/kube/watcher.go:68 > Cannot list labels of the object error="no matches for kind \"Application\" in version \"v1alpha1\""
```

Would it be possible to be able to get basic metadata assuming that resources are valid kubernetes objects? What i'm mostly interested in is the name of of the resource.

**Comment by mustafaakin** [comment]
Unfortunately, in Kubernetes, there is no global role that can read every resource. They need to be typed one by one, I think there is a way to extend the default roles, Aggregated ClusterRoles, but I am not sure how to use it actually.
