### ISSUE TITLE
file sink is not available with distroless image.

### ISSUE THREAD

**Issue by youyongsong** [opsgenie/kubernetes-event-exporter#22]
kubernetes-event-exporter is using distroless as base image. But distroless does not have a functioning filesystem. When I set receiver to a file, it will report the file path does not exist. But when I  change the base image to alpine, file sink will work well.

**Comment by mustafaakin** [comment]
File sink is for mostly debugging purposes in local. IF you really want to use it in the Pod for some reason, distroless is not the cause, the problem is the folders not existing, it will not create the folders.
