### ISSUE TITLE
visible events

### ISSUE THREAD

**Issue by tsn77130** [opsgenie/kubernetes-event-exporter#26]
Hi,

Is there something particular to do to get all events ?
I've only got 'Successfully assigned xxx to yyy' events with standard elasticsearch output

**Comment by mustafaakin** [comment]
There is nothing in particular. They should just work, it does not get the past events, if your cluster does not have any actions, it can have low activity.

**Comment by strowi** [comment]
Not to gravedig.. but for others running into the same problem with elasticsearch:
Check that you are using the correct timestmap filed "metadata.creationTimestamp".;)
