### ISSUE TITLE
Wrting data to elasticsearch through fluentd-aggregator

### ISSUE THREAD

**Issue by chandankumar4** [opsgenie/kubernetes-event-exporter#28]
Is there any way to write data in elastic search through `fluentd-aggregator` so that we will not miss any event due to unreachable of elastic search host?

A complete scenario is:
- Let say the elasticsearch is deployed in a different network and it will expose the service to writing the data in it.
- kubernetes-event-exporter use the exposed elasticsearch IP and write the data in it. But what happens when the exposed IP  get down for some time then we lost the event at that time but if we redirect it through the fluentd-aggregator then the fluentd-aggregator will buffer the event if elasticsearch is unreachable

**Comment by mustafaakin** [comment]
I verify the reason, but it's not the case for only Elasticsearch output. We also need to do it for the other outputs, so instead of relying on fluentd-aggregator, I believe there should be a buffer mechanism in the kubernetes-event-exporter.
