### ISSUE TITLE
Publish latest docker image

### ISSUE THREAD

**Issue by gavinbunney** [opsgenie/kubernetes-event-exporter#29]
I was chasing down an issue with webhooks `layout` not supporting inner-array fields properly, and turns out you've already pushed a fix for it :D However it's not available in the latest docker hub image.

Could you publish a new binary version to GitHub and a new docker image to docker hub?

Thanks!

![power-rangers](https://user-images.githubusercontent.com/409207/76128028-14742a80-5fb8-11ea-90d7-57c2b160148a.gif)

**Comment by mustafaakin** [comment]
I was waiting one PR to be merged, and it didn't come through, so I forgot the upload the image.  I just published 0.5 right now. Thanks! 

https://hub.docker.com/layers/opsgenie/kubernetes-event-exporter/0.5/images/sha256-6f517dadcc50b8702b98900382433b9b00c8140f04d398086fe65e58932239d8?context=explore
