### ISSUE TITLE
Not all kinds of events are logged

### ISSUE THREAD

**Issue by klimov-gett** [opsgenie/kubernetes-event-exporter#33]
Pretty much what the title says. For instance i noticed "UpdatedLoadBalancer", "FailedGetScale", "NodeNotReady", "NodeReady", "SuccessfulRescale", etc.

Might be due to RBAC and the default role suggested in the config. Will investigate in this direction, but would also appreciate a hint.

**Comment by mustafaakin** [comment]
Hello, as long as it is an event object, it should be catched, I'm not sure what actually is going on here. It should only happen if the events are published with a different API gropup.

**Comment by mustafaakin** [comment]
@tbsoares Unfortunately Kubernetes does not publish OOMKiled as an event. See https://github.com/kubernetes/kubernetes/issues/38532 and https://github.com/kubernetes/kubernetes/issues/69676 

Relying on status and exporting as a metric is wrong IMO, there is a tool I found on to publish events: https://github.com/xing/kubernetes-oom-event-generator
