### ISSUE TITLE
Make it work without cluster scope

### ISSUE THREAD

**Issue by sderosiaux** [opsgenie/kubernetes-event-exporter#42]
Hi,
I'm working on a project using a large shared kubernetes cluster in the company and we don't have the permissions to define ClusterRoles. Trying to start event-exporter obviously fails (just to monitor my namespace). Is it possible to make it work without ClusterRole ?

**Comment by mustafaakin** [comment]
Hello, it is possible to watch only a namespace, but to make that change easily, the tool would be able to watch only a single namespace. I think it's a fair assumption to make in order to keep things simple.

**Comment by chaurasiya** [comment]
@mustafaakin 
Hi,
I've similar requirement. What should I change to make it work without having permissions to define ClusterRoles? May be just a hint, where to start would be really helpful for workaround.
Thanks

**Comment by chaurasiya** [comment]
@mustafaakin 
I see we can make it work by using this config build https://github.com/opsgenie/kubernetes-event-exporter/blob/d6b6842cebb23142a2c07f524ef8968ef9300a46/pkg/kube/client.go#L30
At this point by default the tool is using clusterConfig. I can modify it for my purpose to make it work. 
Actually I'm facing an issue while building the docker image. Can you help me resolving the following issue?
![image](https://user-images.githubusercontent.com/16851548/83106617-679eda80-a0da-11ea-8f25-2252797fbf2d.png)
