### ISSUE TITLE
Log level configuration

### ISSUE THREAD

**Issue by hoboroten** [opsgenie/kubernetes-event-exporter#43]
It would be great to be able to switch logging level using configmap and/or env variables.

**Comment by mustafaakin** [comment]
Right now its configured via the config file (which is probably a configmap), and it requires refreshing the pod to change it. So the configmap or env variables would. Would not that solve your problem?

**Comment by vulcanUPB** [comment]
Hello, 

I have tried to change the log level using the 01-config.yaml file, but after refreshing the pod but the changes are not picked up, the log level it's still info. Also changed the type of events I want notifications of but instead I get all the event that are generated by a pod. 

I have attached the the config yaml file, maybe there is something missing from the file.
[01-config.txt](https://github.com/opsgenie/kubernetes-event-exporter/files/4769646/01-config.txt)

**Comment by mustafaakin** [comment]
@vulcanUPB I tested it locally, but it works? I changed the conf file and rerun the binary and the log level changed. Maybe it's a kubernetes issue?

**Comment by vulcanUPB** [comment]
> 
> 
> @vulcanUPB I tested it locally, but it works? I changed the conf file and rerun the binary and the log level changed. Maybe it's a kubernetes issue?

What version of kubernetes are you using?

**Comment by mustafaakin** [comment]
It's 1.14, Minikube.
