### ISSUE TITLE
Microsoft Team webhook -"Summary or Text is required."

### ISSUE THREAD

**Issue by lesh366** [opsgenie/kubernetes-event-exporter#46]
Cant send team webhook, missing mandatory field:

Cannot send event error="not 200: Summary or Text is required."

Am i missing something?

Thanks

**Comment by lesh366** [comment]
i will add teams sink and open a pull request

**Comment by mustafaakin** [comment]
I think a proper integration would be better. Thanks!

**Comment by lesh366** [comment]
Hi,
i've added microsoft teams support, how can i open a pull request?
