### ISSUE TITLE
Elasticsearch sync specifies optional layout - but not supported in code

### ISSUE THREAD

**Issue by samer-shami** [opsgenie/kubernetes-event-exporter#48]
The `README.md` states that the Elasticsearch sink supports the optional `layout` config parameter.

However reading through https://github.com/opsgenie/kubernetes-event-exporter/blob/master/pkg/sinks/elasticsearch.go seems to indicate that `layout` is not a config item like the sinks `kinesis`, `sqs`.

Is it possible to add the `layout` functionality to Elasticsearch as well to match the documentation?

**Comment by mustafaakin** [comment]
You are right, it will be fixed in the next release.
