### ISSUE TITLE
Allow logs to be formatted in json

### ISSUE THREAD

**Issue by jaydp17** [opsgenie/kubernetes-event-exporter#52]
We're pretty-printing the logs for better usability, which makes sense when the user is directly looking at the logs from the container.

But most people running the event-exporter in their kubernetes clusters will be pushing these logs to some centralized logging system, which may or may not deal properly with colored logs & non-json logs.

It'd be cool if we allow an option to output the logs in json.

Let me know if this sounds like something we'd like to merge in this project, if so I'll go ahead & create a PR

**Comment by mustafaakin** [comment]
Sure, I will make it an option.
