### ISSUE TITLE
Error when building from docker file

### ISSUE THREAD

**Issue by jeffreyt** [opsgenie/kubernetes-event-exporter#54]
Hi, I'm interested in testing out this project but I'm having trouble building the image for my self.  I'm running Linux Mint 19.2 with Docker version 19.03.6, build 369ce74a3c.

When I run

> docker build .

instead of building successfully, results in
...
> Step 4/7 : RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO11MODULE=on go build -mod=vendor -v -a -o /main .
>  ---> Running in 5cee51768c01
> go: inconsistent vendoring in /app:
> 	cloud.google.com/go@v0.38.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
> 	github.com/Masterminds/goutils@v1.1.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt

...

> run 'go mod vendor' to sync, or use -mod=mod or -mod=readonly to ignore the vendor directory
> The command '/bin/sh -c CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO11MODULE=on go build -mod=vendor -v -a -o /main .' returned a non-zero code: 1

I also noticed the same error trace when looking at some of the github build tests 
https://github.com/opsgenie/kubernetes-event-exporter/runs/637785627

I apologize, I'm still very much a beginner in golang so some of this is a bit beyond me.  Perhaps something is different in my setup or the image for golang:1.14 was recently updated?  Any help would be appreciated.

Also I'm only interested in building and running from a container and don't want to run anything installed locally.

**Comment by jeffreyt** [comment]
Sorry the answer is right there in the error code, it looks like running `go mod vendor` updates the `vendor/modules.txt` file for version compatibility.  I tried both adding directly to dockerfile and just doing locally which updates the txt file, they both work.  The latter probably makes more sense I think.  

Although, I'm kind of curious as to why other people may or may not have the same issue.  I would assume it would break for everyone?  Anyway happy to close the issue but wouldn't mind seeing some feedback before doing so.

**Comment by mustafaakin** [comment]
Yeah, it breaks for everyone when switched to 1.14. It will be fixed in the next release.
