### ISSUE TITLE
Treat all 2xx response code as valid when using the webhook receiver

### ISSUE THREAD

**Issue by floriannadaud** [opsgenie/kubernetes-event-exporter#57]
### Description

I'm sending events to loki with a webhook configuration.
Events are pushed and accepted with a `204` response code from loki

However, because the status code is not `200`, logs are showing this error:
```
2020-06-19T13:27:31Z DBG app/pkg/exporter/channel_registry.go:59 > Cannot send event error="not 200: " event="Started container xxxxxxxxxxxxxxxxx" sink=loki
```

kubernetes-event-exporter only consider `http.StatusOK` as a correct response code from [this bit of code](https://github.com/opsgenie/kubernetes-event-exporter/blob/master/pkg/sinks/webhook.go#L54)

### Proposed solution

Treat all 2xx response code as valid

**Comment by mustafaakin** [comment]
Yes, just merged a code to treat 201 as well, but it might be better just to allow all 2xx

**Comment by bygui86** [comment]
@floriannadaud can you share the configuration you used to send events to loki?

thanks a lot in advance for your help!!
