### ISSUE TITLE
Clusterrole is missing

### ISSUE THREAD

**Issue by mrueg** [opsgenie/kubernetes-event-exporter#61]
https://github.com/opsgenie/kubernetes-event-exporter/blob/master/deploy/00-roles.yaml#L19 mentions a role called "view", but it's not defined. Can you help me out providing the right RBAC settings here?

**Comment by mustafaakin** [comment]
I think it should be included in default Kubernetes rules,  search for **view** https://kubernetes.io/docs/reference/access-authn-authz/rbac/ 

An example: 

> kubectl create rolebinding myappnamespace-myapp-view-binding --clusterrole=view --serviceaccount=myappnamespace:myapp --namespace=acme

**Comment by mrueg** [comment]
Ah forgot about the defaults, thanks!
