### ISSUE TITLE
wrong registry?

### ISSUE THREAD

**Issue by pathcl** [opsgenie/kubernetes-event-exporter#7]
Just tried to deploy it using https://github.com/opsgenie/kubernetes-event-exporter/blob/master/deploy/02-deployment.yaml

But.. 
```
 $ docker pull  docker.pkg.github.com/opsgenie/kubernetes-event-exporter/exporter:0.2
Error response from daemon: Get https://docker.pkg.github.com/v2/opsgenie/kubernetes-event-exporter/exporter/manifests/0.2: no basic auth credentials
```

**Comment by pathcl** [comment]
Another issue easy to solve:

E1213 09:22:17.091859       1 reflector.go:125] pkg/kube/watcher.go:84: Failed to list *v1.Event: events is forbidden: User "system:serviceaccount:monitoring:event-exporter" cannot list resource "events" in API group "" at the cluster scope

**Comment by mustafaakin** [comment]
Fixed the link, we have logged in to the Github packages in our environment, and did not notice the issue, because even though the Github packages are public, they still require login.

For the role part, the role subject name was `exporter`, and changed it to the `event-exporter` to fix.
